version: '3'

volumes:
  questdb_data: {}

services:
  # dashboard:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - celeryworker
  #     - questdb
  #   restart: always
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   ports:
  #     - '8050:8050'
  #   command: /app/scripts/start.sh

  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    command: /app/scripts/start_worker.sh

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  questdb:
    image: 'questdb/questdb:latest'
    volumes:
      - questdb_data:/root/.questdb/db
    ports:
      - '9000:9000'
      - '8812:8812'
