version: "3"

volumes:
  questdb_data: {}

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /app/scripts/start.sh
    env_file:
      - .env
    depends_on:
      - questdb
      - redis
    ports:
      - "8050:8050"

  dashboard-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /app/scripts/start_worker.sh
    env_file:
      - .env
    depends_on:
      - dashboard

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  questdb:
    image: "questdb/questdb:latest"
    volumes:
      - questdb_data:/root/.questdb/db
    ports:
      - "9000:9000"
      - "8812:8812"
